# Multiple Linear Regression Example               
Multiple Linear regression implementation with TensorFlow v2 library.     

This example is using a low-level approach to better understand all mechanics behind the training process.

Original Author: Aymeric Damien        
Project: https://github.com/aymericdamien/TensorFlow-Examples/

The original notebook has code for simple linear regression, I changed that to reflect my learning of `Multiple Linear Regression`.

In [121]:
import tensorflow as tf
import numpy as np
rng = np.random

In [140]:
LR = 0.01
TRAIN_STEP = 1000
DISPLAY_STEP = 50

X = np.array([[3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
              7.042,10.791,5.313,7.997,5.654,9.27,3.1],[3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
              7.042,10.791,5.313,7.997,5.654,9.27,3.1],[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]])
Y = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
              7.042,10.791,5.313,7.997,5.654,9.27,3.1])

W = tf.Variable(rng.randn(X.shape[0],1), name="weight")

In [141]:
def linear_regression(x):
  return x.T @ W

In [142]:
def mean_square(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true.reshape(-1,1)))

In [143]:
optimizer = tf.optimizers.SGD(LR)

In [144]:
def run_optimization():

  with tf.GradientTape() as g:
    pred = linear_regression(X)
    loss = mean_square(pred, Y)

  # Computer gradients
  gradients = g.gradient(loss, [W])

  optimizer.apply_gradients(zip(gradients, [W]))

In [145]:
for step in range(1, 2500 + 1):
    # Run the optimization to update W and b values.
    run_optimization()
    
    if step % DISPLAY_STEP == 0:
        pred = linear_regression(X)
        loss = mean_square(pred, Y)
        print("step: %i, loss: %f" % (step, loss))

step: 50, loss: 0.101786
step: 100, loss: 0.079632
step: 150, loss: 0.062300
step: 200, loss: 0.048741
step: 250, loss: 0.038132
step: 300, loss: 0.029833
step: 350, loss: 0.023339
step: 400, loss: 0.018260
step: 450, loss: 0.014285
step: 500, loss: 0.011176
step: 550, loss: 0.008744
step: 600, loss: 0.006841
step: 650, loss: 0.005352
step: 700, loss: 0.004187
step: 750, loss: 0.003276
step: 800, loss: 0.002563
step: 850, loss: 0.002005
step: 900, loss: 0.001569
step: 950, loss: 0.001227
step: 1000, loss: 0.000960
step: 1050, loss: 0.000751
step: 1100, loss: 0.000588
step: 1150, loss: 0.000460
step: 1200, loss: 0.000360
step: 1250, loss: 0.000281
step: 1300, loss: 0.000220
step: 1350, loss: 0.000172
step: 1400, loss: 0.000135
step: 1450, loss: 0.000105
step: 1500, loss: 0.000082
step: 1550, loss: 0.000065
step: 1600, loss: 0.000050
step: 1650, loss: 0.000039
step: 1700, loss: 0.000031
step: 1750, loss: 0.000024
step: 1800, loss: 0.000019
step: 1850, loss: 0.000015
step: 1900, loss: 0.0

In [146]:
X.T @ W

<tf.Tensor: shape=(17, 1), dtype=float64, numpy=
array([[ 3.30118656],
       [ 4.40084301],
       [ 5.50049946],
       [ 6.71012155],
       [ 6.93005284],
       [ 4.16891546],
       [ 9.77816305],
       [ 6.18228646],
       [ 7.58984671],
       [ 2.16854041],
       [ 7.04201786],
       [10.78984699],
       [ 5.31355786],
       [ 7.9967196 ],
       [ 5.65445136],
       [ 9.26932202],
       [ 3.10124902]])>

In [148]:
Y.reshape(-1,1)

array([[ 3.3  ],
       [ 4.4  ],
       [ 5.5  ],
       [ 6.71 ],
       [ 6.93 ],
       [ 4.168],
       [ 9.779],
       [ 6.182],
       [ 7.59 ],
       [ 2.167],
       [ 7.042],
       [10.791],
       [ 5.313],
       [ 7.997],
       [ 5.654],
       [ 9.27 ],
       [ 3.1  ]])